services:
  db:
    image: postgres:18.1-bookworm
    container_name: local-llm-chat-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${password}
    ports:
      - '5432:5432'
    volumes:
      - local_llm_chat_db_storage:/var/lib/postgresql

volumes:
  local_llm_chat_db_storage:
